{
  "__PACKAGE_UIDS__", " ",
  "__CFG_MAX_LOCAL_VARIABLES__", " 	        100",
  "__SAVE_EXTENSION__", " \".o\"",
  "__DEFAULT_PRAGMAS__", " PRAGMA_WARNINGS + PRAGMA_STRICT_TYPES + PRAGMA_SAVE_BINARY",
  "__CONFIG_FILE_DIR__", " \"/u/tim/COMP/bin\"",
  "__HEARTBEAT_INTERVAL__", " 1000000",
  "__NO_LIGHT__", " ",
  "__SYSMALLOC__", " ",
  "__RESTRICTED_ED__", " ",
  "__ARGUMENTS_IN_TRACEBACK__", " ",
  "__AUTO_TRUST_BACKBONE__", " ",
  "__SMALL_STRING_SIZE__", "     100",
  "__HEART_BEAT_CHUNK__", "      64",
  "__PACKAGE_CONTRIB__", " ",
  "__RECEIVE_SNOOP__", " ",
  "__RUNTIME_LOADING__", " ",
  "__OLD_ED__", " ",
  "__CACHE_STATS__", " ",
  "__LARGE_STRING_SIZE__", "     1000",
  "__APPLY_CACHE_BITS__", " 12",
  "__BINARIES__", " ",
  "__STRING_STATS__", " ",
  "__SANE_EXPLODE_STRING__", " ",
  "__CFG_MAX_CALL_DEPTH__", "			30",
  "__CFG_MAX_EFUN_SOCKS__", " 			16",
  "__LOG_CATCHES__", " ",
  "__MAX_SAVE_SVALUE_DEPTH__", " 25",
  "__MUDLIB_ERROR_HANDLER__", " ",
  "__CFG_EVALUATOR_STACK_SIZE__", "		100000",
  "__CALLOUT_CYCLE_SIZE__", " 32",
  "__DROP_CORE__", " ",
  "__LPC_TO_C__", " ",
  "__PACKAGE_SOCKETS__", " ",
  "__CFG_LIVING_HASH_SIZE__", "			256",
  "__THIS_PLAYER_IN_CALL_OUT__", " ",
  "__NONINTERACTIVE_STDERR_WRITE__", " ",
  "___OPTIONS_H___", " ",
  "__MESSAGE_BUFFER_SIZE__", " 4096",
  "__AUTO_SETEUID__", " ",
  "__LARGEST_PRINTABLE_STRING__", " 20000",
  "__PACKAGE_DEVELOP__", " ",
  "__COMMAND_BUF_SIZE__", "      2000",
  "__CFG_COMPILER_STACK_SIZE__", "			20000",
  "__PACKAGE_MATH__", " ",
};

#define NUM_OPTION_DEFS 44

